---
- name : Gather all registered virtual machines
  hosts: localhost

  vars_prompt:
    - name: "Your_Password"
      prompt: "Enter_vcenter hostname"
      private: no

  tasks:
  - name: Gather all registered virtual machines
    vmware_vm_facts:
      hostname: vc65.labvmware.local
      username: administrator@vsphere.local
      password: '{{ Your_Password }}'
      validate_certs: no
    delegate_to: localhost
    register: vmfacts
