---
- name: Create a VM from a template
  hosts: vmware
  connection: local
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: 172.180.0.147
      username: root
      password: qwertyuiop
      validate_certs: False
      name: vmansibledebian
      template: VM1
      datacenter: Datacenter
      folder: /[FreeNAS2]/
      state: poweredoff
      wait_for_ip_address: yes
